### ISSUE TITLE
CREATE ACCOUNT TO VIEW AND EDIT COMMENTS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Events-and-Bookings#12]
EPIC: User Profile

As a **User** I can **create an account** so that **I can view and edit my comments**.

**Acceptance Criteria**
- A user can create an account with their email.

- A user can log in once the account has been created.

- A user can see their approved and not yet approved comments.

- A user can edit their comments once logged in.

**Tasks**
- [x] Set up a login page.
- [x] Add a link in the homepage to the login page.
- [x] Implement registration functionality.
- [x] Test login feature.
- [x] Link User's profile to their comments so they can make any amendments.
