### ISSUE TITLE
ADD A COMMENT

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Events-and-Bookings#13]
EPIC: Events Page

As a **User** I can **visit the site** so that **I can leave a comment**.

**Acceptance Criteria**
- Users can access the events' comments page from the homepage.

- Users can leave a comment on any event.

**Tasks**
- [x] Set up comments section on event page.
- [x] Comments section is visible to users, but only approved comments are displayed.
- [x] Set up a database to store comments.
- [x] Plan Model for Comments.
