### ISSUE TITLE
WRTIE REVIEWS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Events-and-Bookings#14]
EPIC: Reviews Page

As a **User** I can **visit the site** so that **I can leave a review**.

**Acceptance Criteria**
- Users can access the venue's review page from the homepage.

- Users can leave reviews.

**Tasks**

- [ ] Set up reviews page.
- [ ] Set up a database to store reviews.
- [ ] Plan Model for Reviews.
