### ISSUE TITLE
APPROVE REVIEWS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Events-and-Bookings#15]
EPIC: Reviews Page

As a **Superuser** I can **access reviews** so that **I can approve them**.

**Acceptance Criteria**

- [ ] Acceptance criteria 1

- [ ] Acceptance criteria 2

- [ ] Acceptance criteria 3

**Tasks**

- [ ] Link the bookings form to the homepage.
- [ ] Plan and create model.
- [ ] Test that booking request is received and accessible to Superusers.
