### ISSUE TITLE
CREATE AN ACCOUNT AND VIEW BOOKING REQUESTS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Events-and-Bookings#3]
EPIC: User Profile

As a **User** I can **create an account** so that **I can view my bookings**.

**Acceptance Criteria**
- A user can create an account with their email.

- A user can log in once the account has been created.

- A user can see their past and upcoming bookings when logged in.

- A user can edit their upcoming bookings once logged in.

**Tasks**
- [x] Set up a login page.
- [x] Add a link in the homepage to the login page.
- [x] Implement registration functionality.
- [x] Test login feature.
- [ ] Link User's profile to their booking requests so they can make any amendments.
