### ISSUE TITLE
SUBMIT A BOOKING REQUEST

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Events-and-Bookings#7]
EPIC: Bookings Page

As a **User** I can **visit the site** so that **I can make a booking**.

**Acceptance Criteria**

- Users can access the bookings page from the homepage.

- Users can fill and submit a form with their booking request.

- The form will be accessible only to Superusers.

**Tasks**

- [x] Set up bookings page.
- [x] Add calendar feature to bookings form so users can view and choose a date they'd like to book.
- [x] Set up a database to store bookings.
- [x] Plan Model for Bookings.
