### ISSUE TITLE
VIEW BOOKING REQUESTS

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Deli-Events-and-Bookings#8]
EPIC: Bookings Page

As a **Superuser** I can **access booking requests** so that **I can view and respond to them**.

**Acceptance Criteria**
- A superuser can create an account with their email.

- A superuser can log into their account.

- A superuser can create, edit and delete events.

- A superuser can view booking requests from the admin panel.

**Tasks**

- [x] Set up admin page so that only a superuser can access it.

- [x] All booking requests are accessible from the admin panel.

- [x] Link database with booking requests to admin panel.
